### Listar Carterinhas
GET http://localhost:8080/carterinha/listar

### Cadastrar Carterinha

POST http://localhost:8080/carterinha/cadastrar
Content-Type: application/json

{
  "usuario_id": 1,
  "cpf": "12345678901",
  "rg":	"1234567",
  "dataNascimento": "30/10/1999",
  "telefone": "(45) 99999-9999",
  "curso": "Engenharia de Software",
  "instituicao": "UTFPR",
  "imagem": "teste"
  }

### Logar Usuario
POST http://localhost:8080/usuario/login
Content-Type: application/json

{

    "email": "logintestes@hotmail.com",
    "senha": "senhatestes"

}

### Cadastrar Usuario
POST http://localhost:8080/usuario/cadastrar
Content-Type: application/json

{

    "nomeCompleto": "Gui gp",
    "email": "guilhermegarap@gmail.com",
    "senha": "12345"

}

 